### PR TITLE
[dd-handler] Bump requirement on `chef_handler`

### LINKED ISSUE #338: Unable to test my cookbook w/ ChefSpec when including datadog::dd-handler
I’m using `datadog` v2.5.0.

I have a cookbook, with a recipe that:

``` ruby
include_recipe 'datadog::dd-agent'
include_recipe 'datadog::dd-handler'
```

However, this is the output I get:

```
6) ds_base::monitoring When all attributes are default, on Ubuntu 16.04 converges successfully
   Failure/Error: expect { chef_run }.to_not raise_error

     expected no Exception, got #<LoadError: cannot load such file -- chef/handler/datadog> with backtrace:
       # /var/folders/30/nsmp68z977s8q1x10z4h9_fr0000gn/T/chefspec20160808-17741-60xwg5file_cache_path/cookbooks/datadog/recipes/dd-handler.rb:38:in `from_file'
       # /var/folders/30/nsmp68z977s8q1x10z4h9_fr0000gn/T/chefspec20160808-17741-60xwg5file_cache_path/cookbooks/ds_base/recipes/monitoring.rb:12:in `from_file'
       # ./spec/unit/recipes/monitoring_spec.rb:24:in `block (3 levels) in <top (required)>'
       # ./spec/unit/recipes/monitoring_spec.rb:28:in `block (4 levels) in <top (required)>'
       # ./spec/unit/recipes/monitoring_spec.rb:28:in `block (3 levels) in <top (required)>'
   # ./spec/unit/recipes/monitoring_spec.rb:28:in `block (3 levels) in <top (required)>'
```

If I `chef gem install chef-handler-datadog`, things work properly, but that feels a bit janky.

### PR DESCRIPTION
**Pull request by olivielpeau**
Allows removing the `require` on our handler, since `chef_handler` >= 1.2
can take care of requiring our handler. Should fix #338

Keep installing the `chef_gem` and enabling the handler at compile time
so that the handler can report compilation errors.

Unfortunately we still need to skip the `dd-handler` recipe in `why_run` mode with `chef_handler` `1.4` (see inline comment for link to related issue)

### CODE REVIEW

**Comment by olivielpeau** [comment]
Let's wait a bit before merging this, I want to have a quick look at how the requirement bump would play with "the rest of the world" of community cookbooks

**Comment by olivielpeau** [comment]
Chef 13 seems to require `chef_handler` 2.x (see #406), would also affect this PR.

**Comment by bai** [comment]
:wave: It's almost April and Chef 13 is less than a month away. Are there any blockers on this one — anything I could help with?

**Comment by degemer** [comment]
Hello @bai, https://github.com/DataDog/chef-datadog/pull/414 loosened the requirements on chef_handler which we thought was required for Chef 13. It might actually not be the case (see [this comment on the related chef_handler issue](https://github.com/chef-cookbooks/chef_handler/issues/45#issuecomment-286654695)).

I tested chef 13.0.64 with both chef_handler 1.4.0 & 2.1.0, and it worked in both cases, so I think we're ready. Please let us know if you encounter an issue with it!

If you wanted to use chef_handler 2.x, we'll release 2.9.0 this week that will allow you to do that.

File: metadata.rb [hunk 1]
```diff
@@ -22,7 +22,7 @@
 end
 
 depends          'apt' # We recommend '>= 2.1.0'. See CHANGELOG.md for details
-depends          'chef_handler', '~> 1.1' # We recommend '~> 1.3' with Chef < 12. See CHANGELOG.md for details
+depends          'chef_handler', '~> 1.2' # We recommend '~> 1.3' with Chef < 12. See CHANGELOG.md for details
```
Comment (olivielpeau) [inline metadata.rb]: this should be `>= 1.2`
